DATASET_TYPES = {

"comprehensive_CASP16": {
        "node_features" : [ 
            "amino_hot_encoding",
            "is_interface",

            "IDR_binary",
            "PB_binary",
            "DB_binary",
            "RB_binary",
            "IB_binary",
            "LB_binary",
            "DFL_binary",
            "IDR_propensity",
            "PB_propensity",
            "DB_propensity",
            "RB_propensity",
            "IB_propensity",
            "LB_propensity",
            "DFL_propensity",

            "netsurfp_3.0_disorder",
            "netsurfp_3.0_p[q3_C]",
            "netsurfp_3.0_p[q3_E]",
            "netsurfp_3.0_p[q3_H]",
            "netsurfp_3.0_p[q8_B]",
            "netsurfp_3.0_p[q8_C]",
            "netsurfp_3.0_p[q8_E]",
            "netsurfp_3.0_p[q8_G]",
            "netsurfp_3.0_p[q8_H]",
            "netsurfp_3.0_p[q8_I]",
            "netsurfp_3.0_p[q8_S]",
            "netsurfp_3.0_p[q8_T]",
            "netsurfp_3.0_rsa",
            "netsurfp_3.0_phi",
            "netsurfp_3.0_psi",

            "seqinsite_probability",
            
            "surfaces_self_ddG",

            "model_dssp_phi_angle",
            "model_dssp_psi_angle",
            "model_dssp_relative_asa",
            "model_dssp_secondary_structure",

            "ref_dssp_phi_angle",
            "ref_dssp_psi_angle",
            "ref_dssp_relative_asa",
            "ref_dssp_secondary_structure",

            "ref_intra_ShortestPath_0",
            "ref_intra_ShortestPath_1",
            "ref_intra_ShortestPath_2",
            
            "ref_inter_ShortestPath_0",
            "ref_inter_ShortestPath_1",
            "ref_inter_ShortestPath_2",
            
            "rosetta_dslf_fa13",
            "rosetta_fa_atr",
            "rosetta_fa_dun",
            "rosetta_fa_elec",
            "rosetta_fa_intra_atr",
            "rosetta_fa_intra_rep",
            "rosetta_fa_intra_sol_xover4",
            "rosetta_fa_rep",
            "rosetta_fa_sol",
            "rosetta_hbond_bb_sc",
            "rosetta_hbond_sc",
            "rosetta_lk_ball_wtd",
            "rosetta_omega",
            "rosetta_p_aa_pp",
            "rosetta_pro_close",
            "rosetta_rama_prepro",
            "rosetta_ref",
            "rosetta_total_score",
            "rosetta_yhh_planarity",

            "angle_prot_com",
            "scaled_dist_prot_com",
            "unscaled_dist_prot_com",

            "angle_chain_com",
            "scaled_dist_chain_com",
            "unscaled_dist_chain_com",
            "discounted_dist_chain_com"

        ], 
        "edge_features": [
            "is_inter_chain",
            "model_distance",
            "model_w_d",
            "rosetta_fa_atr_independent",
            "rosetta_fa_rep_independent",
            "rosetta_fa_sol_independent",
            "ref_distance_monomeric",
            "ref_w_d_monomeric",
            "ref_distance_dimeric",
            "ref_w_d_dimeric",
            "ref_contact_dimeric",
            "surfaces_interaction_ddG",
            "model_angle", 
            "ref_angle_monomeric"
        ]   
    },

    "comprehensive": {
        "node_features" : [ 
            "one_hot_encoding",
            "is_interface_node",

            "IDR_binary",
            "PB_binary",
            "DB_binary",
            "RB_binary",
            "IB_binary",
            "LB_binary",
            "DFL_binary",
            "IDR_propensity",
            "PB_propensity",
            "DB_propensity",
            "RB_propensity",
            "IB_propensity",
            "LB_propensity",
            "DFL_propensity",

            "NetSurfP_disorder",
            "NetSurfP_p_q3_C",
            "NetSurfP_p_q3_E",
            "NetSurfP_p_q3_H",
            "NetSurfP_p_q8_B",
            "NetSurfP_p_q8_C",
            "NetSurfP_p_q8_E",
            "NetSurfP_p_q8_G",
            "NetSurfP_p_q8_H",
            "NetSurfP_p_q8_I",
            "NetSurfP_p_q8_S",
            "NetSurfP_p_q8_T",
            "NetSurfP_rsa",
            "NetSurfP_phi",
            "NetSurfP_psi",

            "seqinsite_site_probability",
            
            "surfaces_self_ddG",

            "dssp_features_phi_angle",
            "dssp_features_psi_angle",
            "dssp_features_relative_asa",
            "dssp_features_secondary_structure",

            "alphafold_dssp_phi_angle",
            "alphafold_dssp_psi_angle",
            "alphafold_dssp_relative_asa",
            "alphafold_dssp_secondary_structure",

            "alphafold_intra_ShortestPath_0",
            "alphafold_intra_ShortestPath_1",
            "alphafold_intra_ShortestPath_2",
            
            "cdpred_inter_ShortestPath_0",
            "cdpred_inter_ShortestPath_1",
            "cdpred_inter_ShortestPath_2",
            
            "rosetta_node_feats_dslf_fa13",
            "rosetta_node_feats_fa_atr",
            "rosetta_node_feats_fa_dun",
            "rosetta_node_feats_fa_elec",
            "rosetta_node_feats_fa_intra_atr",
            "rosetta_node_feats_fa_intra_rep",
            "rosetta_node_feats_fa_intra_sol_xover4",
            "rosetta_node_feats_fa_rep",
            "rosetta_node_feats_fa_sol",
            "rosetta_node_feats_hbond_bb_sc",
            "rosetta_node_feats_hbond_sc",
            "rosetta_node_feats_lk_ball_wtd",
            "rosetta_node_feats_omega",
            "rosetta_node_feats_p_aa_pp",
            "rosetta_node_feats_pro_close",
            "rosetta_node_feats_rama_prepro",
            "rosetta_node_feats_ref",
            "rosetta_node_feats_total_score",
            "rosetta_node_feats_yhh_planarity",

            "angle_prot_com",
            "scaled_dist_prot_com",
            "uncaled_dist_prot_com",

            "angle_chain_com",
            "scaled_dist_chain_com",
            "uncaled_dist_chain_com",
            "discounted_dist_chain_com"

        ], 
        "edge_features": [
            "is_inter_chain",
            "model_distance",
            "model_w_d",
            "rosetta_fa_atr_independent",
            "rosetta_fa_rep_independent",
            "rosetta_fa_sol_independent",
            "alphafold_distance",
            "alphafold_w_d",
            "cdpred_distance",
            "cdpred_w_d",
            "cdpred_contact",
            "surfaces_interaction_ddG",
            "model_angle", 
            "alphafold_angle"
        ]   
    }

}

ANGLE_FEATS = set([
    
    #### Node Angles ####

    "dssp_features_phi_angle",
    "dssp_features_psi_angle",
    
    "alphafold_dssp_phi_angle",
    "alphafold_dssp_psi_angle",

    "esmfold_dssp_phi_angle",
    "esmfold_dssp_psi_angle",

    "model_dssp_phi_angle",
    "model_dssp_psi_angle",

    "ref_dssp_phi_angle",
    "ref_dssp_psi_angle",

    "angle_prot_com",
    "angle_chain_com",

    "NetSurfP_phi",
    "NetSurfP_psi",

    "netsurfp_3.0_phi",
    "netsurfp_3.0_psi",

    #### Edge Angles ####

    "model_angle", 
    "alphafold_angle", 
    "esmfold_angle",
    "ref_angle_monomeric"

])

FEATURE_DIMS = {

    "esm_embeddings": 1280,
    "one_hot_encoding": 22,
    "amino_hot_encoding" : 22,
    "is_interface" : 1,
    "is_interface_node": 1,
    "alphafold_intra_ShortestPath_0": 1,
    "alphafold_intra_ShortestPath_1": 1,
    "alphafold_intra_ShortestPath_2": 1,
    "esmfold_intra_ShortestPath_0": 1,
    "esmfold_intra_ShortestPath_1": 1,
    "esmfold_intra_ShortestPath_2": 1,
    "cdpred_inter_ShortestPath_0": 1,
    "cdpred_inter_ShortestPath_1": 1,
    "cdpred_inter_ShortestPath_2": 1,
    "aesop_feats_ddGa": 1,
    "aesop_feats_significant": 1,
    "surfaces_self_ddG": 1,
    "seqinsite_site_probability": 1,
    "seqinsite_probability": 1,
    "dssp_features_phi_angle": 2,
    "dssp_features_psi_angle": 2,
    "dssp_features_relative_asa": 1,
    "dssp_features_secondary_structure": 8,

    "model_dssp_phi_angle": 2,
    "model_dssp_psi_angle" : 2,
    "model_dssp_relative_asa": 1,
    "model_dssp_secondary_structure": 8,

    "ref_dssp_phi_angle": 2,
    "ref_dssp_psi_angle": 2,
    "ref_dssp_relative_asa": 1,
    "ref_dssp_secondary_structure": 8,

    "ref_intra_ShortestPath_0": 1,
    "ref_intra_ShortestPath_1": 1,
    "ref_intra_ShortestPath_2": 1,
    
    "ref_inter_ShortestPath_0": 1,
    "ref_inter_ShortestPath_1": 1,
    "ref_inter_ShortestPath_2": 1,

    "alphafold_dssp_phi_angle": 2,
    "alphafold_dssp_psi_angle": 2,
    "alphafold_dssp_relative_asa": 1,
    "alphafold_dssp_secondary_structure": 8,

    "esmfold_dssp_phi_angle": 2,
    "esmfold_dssp_psi_angle": 2,
    "esmfold_dssp_relative_asa": 1,
    "esmfold_dssp_secondary_structure": 8,

    "netsurfp_3.0_disorder": 1,
    "netsurfp_3.0_p[q3_C]": 1,
    "netsurfp_3.0_p[q3_E]": 1,
    "netsurfp_3.0_p[q3_H]": 1,
    "netsurfp_3.0_p[q8_B]": 1,
    "netsurfp_3.0_p[q8_C]": 1,
    "netsurfp_3.0_p[q8_E]": 1,
    "netsurfp_3.0_p[q8_G]": 1,
    "netsurfp_3.0_p[q8_H]": 1,
    "netsurfp_3.0_p[q8_I]": 1,
    "netsurfp_3.0_p[q8_S]": 1,
    "netsurfp_3.0_p[q8_T]": 1,
    "netsurfp_3.0_rsa": 1,
    "netsurfp_3.0_phi": 2,
    "netsurfp_3.0_psi": 2,

    "NetSurfP_disorder": 1,
    "NetSurfP_p_q3_C": 1,
    "NetSurfP_p_q3_E": 1,
    "NetSurfP_p_q3_H": 1,
    "NetSurfP_p_q8_B": 1,
    "NetSurfP_p_q8_C": 1,
    "NetSurfP_p_q8_E": 1,
    "NetSurfP_p_q8_G": 1,
    "NetSurfP_p_q8_H": 1,
    "NetSurfP_p_q8_I": 1,
    "NetSurfP_p_q8_S": 1,
    "NetSurfP_p_q8_T": 1,
    "NetSurfP_rsa": 1,
    "NetSurfP_phi": 2,
    "NetSurfP_psi": 2,

    "IDR_binary": 1,
    "PB_binary": 1,
    "DB_binary": 1,
    "RB_binary": 1,
    "IB_binary": 1,
    "LB_binary": 1,
    "DFL_binary": 1,
    "IDR_propensity": 1,
    "PB_propensity": 1,
    "DB_propensity": 1,
    "RB_propensity": 1,
    "IB_propensity": 1,
    "LB_propensity": 1,
    "DFL_propensity": 1,

    "binary_DNA-binding_prediction": 1,
    "DNA-binding_propensity": 1,
    "binary_RNA-binding_prediction": 1,
    "RNA-binding_propensity": 1,
    "binary_disorder_prediction": 1,
    "disorder_propensity": 1,
    "binary_linker_prediction": 1,
    "linker_propensity": 1,
    "binary_protein-binding_prediction": 1,
    "protein-binding_propensity": 1,
    
    "rosetta_node_feats_dslf_fa13": 1,
    "rosetta_node_feats_fa_atr": 1,
    "rosetta_node_feats_fa_dun": 1,
    "rosetta_node_feats_fa_elec": 1,
    "rosetta_node_feats_fa_intra_atr": 1,
    "rosetta_node_feats_fa_intra_rep": 1,
    "rosetta_node_feats_fa_intra_sol_xover4": 1,
    "rosetta_node_feats_fa_rep": 1,
    "rosetta_node_feats_fa_sol": 1,
    "rosetta_node_feats_hbond_bb_sc": 1,
    "rosetta_node_feats_hbond_sc": 1,
    "rosetta_node_feats_lk_ball_wtd": 1,
    "rosetta_node_feats_omega": 1,
    "rosetta_node_feats_p_aa_pp": 1,
    "rosetta_node_feats_pro_close": 1,
    "rosetta_node_feats_rama_prepro": 1,
    "rosetta_node_feats_ref": 1,
    "rosetta_node_feats_total_score": 1,
    "rosetta_node_feats_yhh_planarity": 1,

    "rosetta_dslf_fa13": 1,
    "rosetta_fa_atr": 1,
    "rosetta_fa_dun": 1,
    "rosetta_fa_elec": 1,
    "rosetta_fa_intra_atr": 1,
    "rosetta_fa_intra_rep": 1,
    "rosetta_fa_intra_sol_xover4": 1,
    "rosetta_fa_rep": 1,
    "rosetta_fa_sol": 1,
    "rosetta_hbond_bb_sc": 1,
    "rosetta_hbond_sc": 1,
    "rosetta_lk_ball_wtd": 1,
    "rosetta_omega": 1,
    "rosetta_p_aa_pp": 1,
    "rosetta_pro_close": 1,
    "rosetta_rama_prepro": 1,
    "rosetta_ref": 1,
    "rosetta_total_score": 1,
    "rosetta_yhh_planarity": 1,

    "is_inter_chain": 1,
    "model_distance": 1,
    "model_w_d": 1,
    "rosetta_fa_atr_independent": 1,
    "rosetta_fa_rep_independent": 1,
    "rosetta_fa_sol_independent": 1,
    "ref_distance_monomeric": 1,
    "ref_w_d_monomeric": 1,
    "alphafold_distance": 1,
    "alphafold_w_d": 1,
    "esmfold_distance": 1,
    "esmfold_w_d": 1,
    "cdpred_distance": 1,
    "cdpred_w_d": 1,
    "cdpred_contact": 1,
    "surfaces_interaction_ddG": 1,
    "ref_distance_dimeric": 1,
    "ref_w_d_dimeric": 1,
    "ref_contact_dimeric": 1,

    "angle_prot_com": 2,
    "scaled_dist_prot_com": 1,
    "uncaled_dist_prot_com": 1,
    "unscaled_dist_prot_com": 1,

    "angle_chain_com": 2,
    "scaled_dist_chain_com": 1,
    "uncaled_dist_chain_com": 1,
    "unscaled_dist_chain_com": 1,
    "discounted_dist_chain_com": 1,

    "model_angle": 2, 
    "ref_angle_monomeric": 2, 
    "esmfold_angle": 2

}